/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ManajemenInputNilai;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class InputKodeMatkul extends javax.swing.JFrame {

    /**
     * Creates new form InputKodeMatkul
     */
    public InputKodeMatkul() {
        initComponents();
        tampilkanData();
        
        tblMatkul.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tableMatkulMouseClicked(evt);  // Panggil metode untuk menangani klik pada tabel
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtMatkul = new javax.swing.JTextField();
        txtSks = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatkul = new javax.swing.JTable();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode Matkul");

        jLabel2.setText("Nama Matkul");

        jLabel3.setText("sks");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Matkul", "Nama Matkul", "SKS"
            }
        ));
        jScrollPane1.setViewportView(tblMatkul);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSks, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 54, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btnKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String kodeMatkul = txtKode.getText();
        String namaMatkul = txtMatkul.getText();
        String sks = txtSks.getText();

    if (kodeMatkul.isEmpty() || namaMatkul.isEmpty() || sks.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
    } else {
        // Cek apakah data valid
        try (Connection conn = DatabaseConnection.getConnection()) {
            String sql = "INSERT INTO mata_kuliah (kode_matkul, nama_matkul, sks) VALUES (?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, kodeMatkul);
            pst.setString(2, namaMatkul);
            pst.setInt(3, Integer.parseInt(sks));  // Konversi sks ke integer

            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                // Kosongkan form setelah simpan
                txtKode.setText("");
                txtMatkul.setText("");
                txtSks.setText("");
                
                tampilkanData();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data.");
            }
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "SKS harus berupa angka.");
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        updateData();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new Input_Nilai().setVisible(true);  // Menampilkan halaman InputKodeMatkul
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void updateData() {
    String kodeMatkul = txtKode.getText();
    String namaMatkul = txtMatkul.getText();
    String sks = txtSks.getText();

    // Pastikan kode matkul yang dimasukkan sudah ada di database
    if (kodeMatkul.isEmpty() || namaMatkul.isEmpty() || sks.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
        return;
    }

    // Koneksi ke database dan query update
    try {
        Connection conn = DatabaseConnection.getConnection();  // Mengambil koneksi database
        String query = "UPDATE mata_kuliah SET nama_matkul = ?, sks = ? WHERE kode_matkul = ?";
        PreparedStatement pst = conn.prepareStatement(query);
        
        // Set parameter untuk query update
        pst.setString(1, namaMatkul);
        pst.setString(2, sks);
        pst.setString(3, kodeMatkul);

        // Eksekusi query
        int result = pst.executeUpdate();
        
        // Cek hasil update
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.");
            tampilkanData();  // Update tabel setelah perubahan
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal diperbarui.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
}
    
    private void deleteData() {
    String kodeMatkul = txtKode.getText();
    
    // Pastikan kode matkul sudah dipilih
    if (kodeMatkul.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus.");
        return;
    }

    // Koneksi ke database dan query delete
    try {
        Connection conn = DatabaseConnection.getConnection();
        String query = "DELETE FROM mata_kuliah WHERE kode_matkul = ?";
        PreparedStatement pst = conn.prepareStatement(query);
        
        // Set parameter untuk query delete
        pst.setString(1, kodeMatkul);
        
        // Eksekusi query
        int result = pst.executeUpdate();
        
        // Cek hasil delete
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            tampilkanData();  // Update tabel setelah data dihapus
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal dihapus.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
}
    
    private void tableMatkulMouseClicked(java.awt.event.MouseEvent evt) {                                        
    int row = tblMatkul.getSelectedRow();  // Mendapatkan baris yang dipilih
    if (row != -1) {
        // Mengambil data dari tabel dan mengisi textfield
        txtKode.setText(tblMatkul.getValueAt(row, 0).toString());
        txtMatkul.setText(tblMatkul.getValueAt(row, 1).toString());
        txtSks.setText(tblMatkul.getValueAt(row, 2).toString());
    }String kodeMatkul = txtKode.getText();
    
    // Pastikan kode matkul sudah dipilih
    if (kodeMatkul.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus.");
        return;
    }

    // Koneksi ke database dan query delete
    try {
        Connection conn = DatabaseConnection.getConnection();
        String query = "DELETE FROM mata_kuliah WHERE kode_matkul = ?";
        PreparedStatement pst = conn.prepareStatement(query);
        
        // Set parameter untuk query delete
        pst.setString(1, kodeMatkul);
        
        // Eksekusi query
        int result = pst.executeUpdate();
        
        // Cek hasil delete
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            tampilkanData();  // Update tabel setelah data dihapus
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal dihapus.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputKodeMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputKodeMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputKodeMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputKodeMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputKodeMatkul().setVisible(true);
            }
        });
    }
    
    private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Matkul");
    model.addColumn("Nama Matkul");
    model.addColumn("SKS");

    try (Connection conn = DatabaseConnection.getConnection()) {
        String sql = "SELECT * FROM mata_kuliah";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("kode_matkul"),
                rs.getString("nama_matkul"),
                rs.getInt("sks")
            });
        }
        
        // Set model pada JTable
        tblMatkul.setModel(model);

    } catch (SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMatkul;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtMatkul;
    private javax.swing.JTextField txtSks;
    // End of variables declaration//GEN-END:variables
}
