/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ManajemenInputNilai;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class Nilai_Mahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form Nilai_Mahasiswa
     */
    public Nilai_Mahasiswa() {
        initComponents();
        tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNilaiMahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblNilaiMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Mata Kuliah", "Nama Mata Kuliah", "NIM", "Nama", "Nilai"
            }
        ));
        jScrollPane1.setViewportView(tblNilaiMahasiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nilai_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nilai_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nilai_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nilai_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nilai_Mahasiswa().setVisible(true);
            }
        });
    }
    
    private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Matkul");
    model.addColumn("Nama Matkul");
    model.addColumn("NIM");
    model.addColumn("Nama");
    model.addColumn("Nilai");

    try {
        Connection conn = DatabaseConnection.getConnection();
        String query = "SELECT n.kode_matkul, m.nama_matkul, n.nim, p.username, n.nilai " +
                       "FROM nilai n " +
                       "JOIN mata_kuliah m ON n.kode_matkul = m.kode_matkul " +
                       "JOIN pengguna p ON n.nim = p.nim " +
                       "WHERE n.nim = ?";  // Filter berdasarkan NIM yang login

        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, Login.nimMahasiswa);  // Menggunakan NIM yang login
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String kodeMatkul = rs.getString("kode_matkul");
            String namaMatkul = rs.getString("nama_matkul");
            String nim = rs.getString("nim");
            String namaMahasiswa = rs.getString("username");
            String nilai = rs.getString("nilai");
            model.addRow(new Object[]{kodeMatkul, namaMatkul, nim, namaMahasiswa, nilai});
        }

        tblNilaiMahasiswa.setModel(model);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNilaiMahasiswa;
    // End of variables declaration//GEN-END:variables
}
